const LUGARES_ECUADOR = {
    "Azuay": ["Cuenca", "Gualaceo", "Paute", "Santa Isabel"],
    "Bolívar": ["Guaranda", "Chillanes", "Chimbo", "Echeandía"],
    "Cañar": ["Azogues", "Biblián", "Cañar", "La Troncal"],
    "Carchi": ["Tulcán", "Bolívar", "Espejo", "Mira"],
    "Chimborazo": ["Riobamba", "Alausí", "Chambo", "Guano"],
    "Cotopaxi": ["Latacunga", "La Maná", "Pujilí", "Salcedo"],
    "El Oro": ["Machala", "Huaquillas", "Pasaje", "Santa Rosa"],
    "Esmeraldas": ["Esmeraldas", "Atacames", "Quinindé", "San Lorenzo"],
    "Galápagos": ["Puerto Baquerizo Moreno", "Puerto Ayora", "Puerto Villamil"],
    "Guayas": ["Guayaquil", "Daule", "Durán", "Milagro", "Samborondón"],
    "Imbabura": ["Ibarra", "Cotacachi", "Otavalo", "Pimampiro"],
    "Loja": ["Loja", "Catamayo", "Macará", "Saraguro"],
    "Los Ríos": ["Babahoyo", "Quevedo", "Ventanas", "Vinces"],
    "Manabí": ["Portoviejo", "Manta", "Chone", "Montecristi"],
    "Morona Santiago": ["Macas", "Gualaquiza", "Sucúa"],
    "Napo": ["Tena", "Archidona", "El Chaco"],
    "Orellana": ["Francisco de Orellana (Coca)", "Joya de los Sachas"],
    "Pastaza": ["Puyo", "Mera", "Santa Clara"],
    "Pichincha": ["Quito", "Cayambe", "Mejía", "Rumiñahui"],
    "Santa Elena": ["Santa Elena", "La Libertad", "Salinas"],
    "Santo Domingo": ["Santo Domingo"],
    "Sucumbíos": ["Nueva Loja", "Shushufindi"],
    "Tungurahua": ["Ambato", "Baños", "Pelileo"],
    "Zamora Chinchipe": ["Zamora", "Yantzaza"]
};